### ISSUE TITLE
Pre-loading is very long compared to the other streamer of the torrent.

### ISSUE THREAD

**Issue by Nallat** [bbougot/Popcorn#164]
For the same torrent here is the preloading time:
 Torrent:   Rick and Morty Ep10S3 720p From YggTorrent
PopcornTime sh:  16,78s
Popcorn:               1m45,26s
WebTorrent:          10,05s

**Comment by bbougot** [comment]
Actually you can change the preloading time :
Edit the file C:\Users\[USER]\AppData\Local\Popcorn\app-[VERSION]\Popcorn.exe.config
Change MinimumMovieBuffering or MinimumShowBuffering by decreding its value (i.e 5)

Be aware that decreasing the value increase the probability to have a failure when player starts playing the media, because there may not be enough downloaded data.

**Comment by rashid19961** [comment]
Also For me the buffering take a long time, And the download speeds are very slow despite having good seeds ( 50kb)

**Comment by bbougot** [comment]
@rashid19961 Does it occur for every movie/show? Have you tried different configurations (Wifi, ethernet) and different places?

**Comment by rashid19961** [comment]
@bbougot Hi, I have tried several movies one with thousand of seeds others with hundred, some time the movies buffers quite fast (download at 2MB), I havent tried using ethernet and different place, Perhaps my isp throtling torrents at peak times??
