### ISSUE TITLE
[Enhancement] Porting to OSX

### ISSUE THREAD

**Issue by TNoronha** [bbougot/Popcorn#194]
Hey,

Seeing as the project is implemented in WPF, it is difficult to port it to OSX.
Yet, I have some knowledge of C#, specifically in Xamarin. 
What do you think of porting this to Xamarin.Forms in order to support multiple platforms?

Do you think it would be viable? Of course you would have my helping hands on this.

Regards

**Comment by bbougot** [comment]
Thank you for your suggestion, this could be awesome to have Popcorn developed using a cross-platform framework.
Howevere, there is a lot of work behind the current WPF version, and I mean a lot. Porting this project to Xamarin would require a huge amount of work I could not handle mainly because of lacking time and resources to do it.
