### ISSUE TITLE
Maintain chocolatey package

### ISSUE THREAD

**Issue by KuraiAndras** [bbougot/Popcorn#230]
I have been using chocolatey, for some time now, and I just recently discovered, that Popcorn is available there, but the latest release there is 5.0.1

https://chocolatey.org/packages/popcorn

Would you consider distributing and maintaining your application on chocolatey too?

**Comment by Starz0r** [comment]
@bbougot Hey, I'm the maintainer for the Chocolatey package, I went ahead and added version 5.0.6 today. If you want to be maintainer, make an account and I'll add you to the package. Some things to note:

1. We can't use the same NuGet files that are on the GitHub repository because Chocolatey uses a slightly different format.

2. I don't like the fact that you've removed every other version, since I've hardlinked to those versions in the NuGet file, anyone trying to go back to a previous is unable because there is no longer a download link. Is it possible to get all the versions back?

3. I couldn't figure out a way to uninstall Popcorn from the executable once it's installed, some people have requested it, but there is no way for me to do this without cleanly.

4. Can we get Popcorn as an MSI instead of a EXE? Chocolatey has better support for MSI, as it can track what files get placed on the disk, and then when an uninstall event is triggered, can clean up, without the need of invoking a script. This solves 3.

Anyway, thank you for working on Popcorn!

**Comment by John-Weetaker** [comment]
@bbougot Please do not remove the previous release currently when I'm trying install popcorn from choco the link for v5.0.1 is broken

**Comment by bbougot** [comment]
@Starz0r Hey, thanks for the detailed summary of the issues.
Regarding Chocolatey, I've created an account with the same nickname than my Github's account, I can support the package on this platform too. Actually, what I suggest is to add a step in the Appveyor CI script to publish an MSI of each new release directly and automatically to Chocolatey through their API. Thus there will be no more delay in the releasing of Popcorn. I will do this ASAP.

As regards the missing older versions, I decided to clean them out because all of the previous releases prior to 5.0.6 were affected by an issue preventing the auto-updater to apply an update once a new release is being released. So I'd better start from scratch and ensure all the future releases can update automatically seamlessly. Sorry for the inconvenience.

**Comment by bbougot** [comment]
The Popcorn delivery pipeline has been set up like this:

* Issue/Feature request

1. Create a pull request on branch **development** mentioning the issue number (#230)
2. Appveyor will trigger a build, running unit tests and publish artifacts locally
3. Once Appveyor check is fine (no failing unit test), the development branch is mergeable
4. Once development branch is merged, Appveyor will publish new release to Github and Chocolatey

The pipeline is fully autonomous and will prevent any lag in the releasing process.
