### ISSUE TITLE
Shows not updating?

### ISSUE THREAD

**Issue by unniggable** [bbougot/Popcorn#232]
API is not showing newest episode of recently released shows (they are a couple of days old now), is this a normal thing what happens? How long does it usually take to update?

**Comment by PoorPocketsMcNewHold** [comment]
Just to make sure that you are aware (In case I've might I've understood your sentence wrong), Does your new recently released shows up in other versions of Popcorn Time (Or with the API) ? Because it might significate that these aren't available to stream yet. (And the time until your show is being added will depend on from the time that someone will upload this show there, as I'm pretty sure it isn't pulled out automatically from the sources)

**Comment by unniggable** [comment]
Yeah, I can see new episodes on other versions of Popcorn Time and some new movies which I can't see with this API.

**Comment by bbougot** [comment]
I've updated the refresh scheduling of the API, it will sync with the latest sources each day instead of once a week. The fix has been deployed and will be triggered by tomorrow, it should fix the issue.

**Comment by bbougot** [comment]
Should be okay now, closing.
