### ISSUE TITLE
Left Flyout doesn't integrate smoothly with the app

### ISSUE THREAD

**Issue by Stroked** [bbougot/Popcorn#28]
This is the workflow:
1.ClickFlyoutArea
 2.Flyout Exapands and thumbnails adjust from 6/row to 4/row.
  3a. MY click on recent icon didn't register and no trigger to update view. Makes me click on recent button again.
  3b. If I had scrolled down and clicked on a movie, the flyout just collapsed again and now themovie I had selected had to be re-rendered somewhere far from my cursor. 

I don't know how you missed this one. Do you use the app itself,outside of programming on it?

I find the simplest solution would be to keep the flyout open. Don't even expose the option of collapsing it.

Also, the jump feature for the video player itself is annoying too. If that the infrastructure issue or the app itself. I wanted to resume a movie some 40-50mins into the movie and I just couldn't get it to play beyond a limited range. Jumping  a few mins seems fine but jumping over half an hour is totally not working.

**Comment by bbougot** [comment]
A fix has been made along the commit https://github.com/bbougot/Popcorn/commit/f26365a78a89f35943a9d5fa66cadc6cd617c4aa. 

I have created a Hamburger menu which solves the issues you faced. 
Actually, I'm not fan of unused space, this is why I have created a SplitView to let the user hide the menu bar.

Regarding the jump feature of the player, I have recently added a buffer progress indicator, so that the user knows if he can jump or not.
